services:
  tailchat-clearmsg-bot:
    image: tailchat-clearmsg-bot
    ports:
      - 6002:6002
    restart: always
    volumes:
      - ./.env:/app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tailchat-internal
      - default

networks:
  tailchat-internal:
    external: true